@echo off
echo Installing requirements...
pip install -r requirements.txt
echo Running database migrations...
alembic upgrade head
echo Seeding initial data...
python -m app.db.seeds
echo Starting FastAPI server...
uvicorn app.main:app --reload
pause
