"""add_brand_code_field

Revision ID: 47aaa224cee9
Revises: 9d2e8e02ed1e
Create Date: 2025-12-25 10:05:44.233401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47aaa224cee9'
down_revision: Union[str, Sequence[str], None] = '9d2e8e02ed1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_brand_code'), 'brand', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_code'), table_name='brand')
    op.drop_column('brand', 'code')
    # ### end Alembic commands ###
