"""Add technical specifications to Product model

Revision ID: 7911de619a5b
Revises: 36197b7c83bf
Create Date: 2025-12-24 16:12:28.026423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7911de619a5b'
down_revision: Union[str, Sequence[str], None] = '36197b7c83bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('diameter', sa.String(), nullable=True))
    op.add_column('product', sa.Column('length', sa.String(), nullable=True))
    op.add_column('product', sa.Column('material', sa.String(), nullable=True))
    op.add_column('product', sa.Column('flutes', sa.String(), nullable=True))
    op.add_column('product', sa.Column('hardness', sa.String(), nullable=True))
    op.add_column('product', sa.Column('coating', sa.String(), nullable=True))
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('product', 'coating')
    op.drop_column('product', 'hardness')
    op.drop_column('product', 'flutes')
    op.drop_column('product', 'material')
    op.drop_column('product', 'length')
    op.drop_column('product', 'diameter')
    # ### end Alembic commands ###
