"""Add image_url to Category

Revision ID: 9d2e8e02ed1e
Revises: a2e7a88218d8
Create Date: 2025-12-24 16:55:55.684678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2e8e02ed1e'
down_revision: Union[str, Sequence[str], None] = 'a2e7a88218d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image_url')
    # ### end Alembic commands ###
