"""Add promotion and timestamp fields to Product

Revision ID: a2e7a88218d8
Revises: 7911de619a5b
Create Date: 2025-12-24 16:27:32.472627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e7a88218d8'
down_revision: Union[str, Sequence[str], None] = '7911de619a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('on_sale', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'sale_price')
    op.drop_column('product', 'on_sale')
    # ### end Alembic commands ###
